### ISSUE TITLE
Add an "inactive" list

### ISSUE THREAD

**Issue by cassidoo** [sw-yx/devtools-angels#36]
**Is your feature request related to a problem? Please describe.**
I want to remove myself from the list temporarily to save my inbox a bit while I don't have the capital, but like having the connections.

**Describe the solution you'd like**
A list at the bottom of like "inactive/past" angels so that names aren't lost, but the list shows some history of the group

**Describe alternatives you've considered**
I could also just delete myself and come back later, lol

**Comment by sw-yx** [comment]
for sure i want to keep you on haha
